### ISSUE TITLE
No longer works in 2.3

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/ShowCrosshair#1]
```
drawBackgroundForLayer_: 'NSUnknownKeyException - [<GlyphsToolSelect 0x6180002beba0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key draggCurrent.'
```

I believe the issue is this line:
https://github.com/mekkablue/ShowCrosshair/blob/master/ShowCrosshair.glyphsReporter/Contents/Resources/Crosshair.py#L110

**Comment by mekkablue** [comment]
Yes, it is incompatible with the current betas. But there is nothing I can do at the moment. I will have a running version again for the stable 2.3.

**Comment by weiweihuanghuang** [comment]
Thanks, I will wait for then.

**Comment by weiweihuanghuang** [comment]
Any chance for code to draw something at the location of the mouse (no need to detect mouse down just always at the mouse?)

**Comment by weiweihuanghuang** [comment]
Any chance for code to draw something at the location of the mouse (no need to detect mouse down just always at the mouse?). I want to create a cursor plugin 😁

**Comment by mekkablue** [comment]
No. Not yet, at least. The way the API is currently implemented would not allow that.

**Comment by weiweihuanghuang** [comment]
Is this ready yet 💃 😄
