### ISSUE TITLE
Toggle coordinates does not seem to work (10.9.5)

### ISSUE THREAD

**Issue by synthview** [mekkablue/ShowCrosshair#4]
Hi,
I see no coordinates displaying even after toggling many times and restarting the app twice :/
In addition, the crosshair does not move with the cursor, I have to click to get it move.
Mac OS 10.9.5
G 2.4.1 (976)

Thanks

**Comment by mekkablue** [comment]
May be an OS issue. I can only test on Sierra.

**Comment by synthview** [comment]
:( Ok 
tried to install commits from September 2016 and then may 2016 but crosshair does not appear at all :( (And I’m quite sure it was up to date before the 21th of september commit)

**Comment by mekkablue** [comment]
Anything in Console.app?

**Comment by synthview** [comment]
not sure they’re relevant. I have these messages both with or without the plugin installed.

27/02/17 09:56:12,054 Glyphs[50808]: Invalid color System, labelColor (warning given only once)

27/02/17 09:57:13,600 Glyphs[50876]: Error loading /Library/Python/2.7/site-packages/vanilla/externalFrameworks/RBSplitView/RBSplitView.framework/RBSplitView:  dlopen(/Library/Python/2.7/site-packages/vanilla/externalFrameworks/RBSplitView/RBSplitView.framework/RBSplitView, 265): no suitable image found.  Did find:
	/Library/Python/2.7/site-packages/vanilla/externalFrameworks/RBSplitView/RBSplitView.framework/RBSplitView: file too short

27/02/17 09:57:14,510 Glyphs[50876]: Could not connect the action actionPopup: to target of class RMXMonospacer

27/02/17 09:57:14,532 Glyphs[50876]: Could not connect the action actionPopup: to target of class RMXScaler

27/02/17 09:57:14,698 WindowServer[145]: common_reenable_update: UI updates were finally reenabled by application "Glyphs" after 2.88 seconds (server forcibly re-enabled them after 1.00 seconds)

27/02/17 09:57:15,931 WindowServer[145]: disable_update_timeout: UI updates were forcibly disabled by application "Glyphs" for over 1.00 seconds. Server has re-enabled them.

27/02/17 09:57:16,422 WindowServer[145]: common_reenable_update: UI updates were finally reenabled by application "Glyphs" after 1.49 seconds (server forcibly re-enabled them after 1.00 seconds)

**Comment by synthview** [comment]
I also notice that the lat version of your plugin shows crosshair only when “show stem thickness” is activated too. https://github.com/RafalBuchner/StemThickness

**Comment by mekkablue** [comment]
Please try disabling all plugins except Crosshair. What happens then?

**Comment by synthview** [comment]
Hi,
I’ve deleted everything from repositories and plugins folders and reinstalled one by one to plugins (repositories is empty now).
Crosshair seems to work now, however but coordinates never show :/ 
And I dislike the fact we see the crosshair even in text mode. Would it be possible to set a parameter similar to Glyphs.intDefaults["TextModeNumbersThreshold"] = 300

**Comment by mekkablue** [comment]
> Crosshair seems to work now, however but coordinates never show :/

Coordinates trigger an API call that is possibly not available in 10.9. I can try and catch it with a try/except. And there seems to be a conflict with one of the other plug-ins.

>  I dislike the fact we see the crosshair even in text mode.

The whole point of toggling Crosshair was to switch on a universal crosshair, visible everywhere. Or did I get that wrong, @Tosche? Toggling it again makes it available while dragging only.

**Comment by synthview** [comment]
On 28/02/17 13:13, Rainer Erich Scheichelbauer wrote:
>
>     Crosshair seems to work now, however but coordinates never show :/
>
> Coordinates trigger an API call that is possibly not available in 
> 10.9. I can try and catch it with a try/except. And there seems to be 
> a conflict with one of the other plug-ins.
>
The quirky thing is I reinstalled all of them
>
>     I dislike the fact we see the crosshair even in text mode.
>
> The whole point of toggling Crosshair was to switch on a universal 
> crosshair, visible everywhere. Or did I get that wrong, @Tosche 
> <https://github.com/Tosche>? Toggling it again makes it available 
> while dragging only.
>
personally I find it useful in edit mode

**Comment by Tosche** [comment]
Yes, I wanted to have it visible when I am editing outlines, but the text tool can be an exception.

**Comment by mekkablue** [comment]
The latest update should fix that.
