### ISSUE TITLE
crosshair & show Stem thickness no not refresh views on mouseMove

### ISSUE THREAD

**Issue by synthview** [mekkablue/ShowCrosshair#5]
Hello!
since Version 2.4.2 (987) or the one just before, plugins that should redraw at each mouse-move, don’t. I have to click to see the state change. 

Maybe this message from console is relevant?

11/03/17 13:48:03,275 Glyphs[3034]: Traceback (most recent call last):
  File "GlyphsApp/__init__.py", line 922, in __addCallback__
AttributeError: 'objc.python_selector' object has no attribute '__self__'

**Comment by mekkablue** [comment]
Yes that is relevant. Something seems to be broken in the py wrapper of 987. Not sure I can do much from within the plug-in code. We may have to wait for the next cutting edge version.

**Comment by mekkablue** [comment]
Works again in Version 991.
